const usernames =
  'crawlbulbous\n' +
  'drearynuclei\n' +
  'civicchild\n' +
  'largestbud\n' +
  'youthunicycle\n' +
  'wilsontowels\n' +
  'fabbitpromoter\n' +
  'cryscrooge\n' +
  'huddleecstasy\n' +
  'duckvincenzo\n' +
  'juryuniversity\n' +
  'plornishcowardice\n' +
  'starsubway\n' +
  'brringyorkshire\n' +
  'kedgejackanapes\n' +
  'gratitudexeta\n' +
  'fechlinlandlord\n' +
  'dudgeonstamp\n' +
  'dynastyethnic\n' +
  'cashiersneak\n' +
  'fligdoe\n' +
  'parmesanjoliette\n' +
  'crisparkleepilepsy\n' +
  'cahootsstranger\n' +
  'severalstunt\n' +
  'highmuneral\n' +
  'taliskernose\n' +
  'illinoisforswear\n' +
  'bottonassault\n' +
  'nativityparachute\n' +
  'hydrantchild\n' +
  'moorsheaddoorway\n' +
  'poalblog\n' +
  'paragoneskimo\n' +
  'femaleaffirm\n' +
  'tastehanded\n' +
  'annualswin\n' +
  'meguntie\n' +
  'peesyproofs\n' +
  'nationdelouse\n' +
  'blathershocuspocus\n' +
  'coasterwaffle\n' +
  'facialranked\n' +
  'encorevelvety\n' +
  'fenceplanemo\n' +
  'cyandyechemistry\n' +
  'avishomework\n' +
  'improvefiscally\n' +
  'gabbrodisburse\n' +
  'sorrelfarm' +
  'pechoraplanner\n' +
  'bodminsneeze\n' +
  'theorybicycling\n' +
  'dollhouseverb\n' +
  'catenalutchet\n' +
  'singtopic\n' +
  'millooksilver\n' +
  'wraysburyfondue\n' +
  'divergentreply\n' +
  'economicstubborn\n' +
  'noveltyplatypus\n' +
  'flossxiamen\n' +
  'stitchedsikes\n' +
  'warblingveal\n' +
  'relievedoverstate\n' +
  'birthcharming\n' +
  'reappearpackage\n' +
  'stimmingspring\n' +
  'constructionrecently\n' +
  'mudstrum\n' +
  'covetgrudging\n' +
  'crediblyhead\n' +
  'apacheemm\n' +
  'dancedeliverer\n' +
  'stopperhandgun\n' +
  'rookspoon\n' +
  'handsawbatch\n' +
  'brigaderock\n' +
  'taxonomymailbox\n' +
  'llynfienrick\n' +
  'includedgore\n' +
  'decayferry\n' +
  'pebblesoversized\n' +
  'beestockey\n' +
  'removedbug\n' +
  'dressmustering\n' +
  'populationbeneficent\n' +
  'sizabledelta\n' +
  'blahgrandkid\n' +
  'unlivableannounces\n' +
  'grantstalus\n' +
  'gazingrounding\n' +
  'differencetint\n' +
  'verderink\n' +
  'whammoppings\n' +
  'rangepajamas\n' +
  'vardennicholas\n' +
  'patriarchtoggi\n' +
  'rankedpledge\n' +
  'unnoticedmosquito';

const FakeUserNames = usernames.split('\n');
module.exports = FakeUserNames;
